config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  locales = I18n.available_locales.join('|')
  scope '(:locale)', locale: /#{locales}/ do
    devise_for :users
    # Defines the root path route ("/")
    # root "articles#index"
    root 'posts#index'
    resources :posts
    resources :spaces do
      resources :users, only: %i[create], controller: 'spaces/users'
      resources :products
      resources :items
      resources :suppliers
      resources :orders
      resources :sales
    end
    resources :orders, only: %i[] do
      resource :purchases, only: %i[create update destroy]
    end
    resources :products, only: %i[] do
      resource :sales, only: %i[create  destroy], controller: 'products/sales'
    end


    resources :links, only: %i[show create destroy], param: :sku
    resources :users, only: %i[index edit update destroy]
    get '/open-modal', to: 'pages#open_modal', as: 'open_modal'
  end
end

app/models/concerns/spaces/software.rb
# frozen_string_literal: true

module Spaces
  module Software
    extend ActiveSupport::Concern

    SOFTWARES = %i[none l_addition square tiller zelty].freeze

    included do
      attr_accessor :token, :restaurant_key

      validate :software_already_connected?
      after_commit :link_with_zelty, if: proc { !software_connected_at? && zelty? }
    end

    def zelty?
      software == 'zelty'
    end

    def software_already_connected?
      return false unless software_changed? && software_connected_at?

      errors.add(:software, :already_connected)
    end

    def link_with_zelty
      Spaces::Zelty::Import.new(self).import
      Spaces::Zelty::Connect.new(self).connect
      self.software_connected_at = Time.current
    rescue StandardError
      errors.add(:software, 'failed to connect')

      false
    end
  end
end

app/models/space.rb
# frozen_string_literal: true

class Space < ApplicationRecord
  include Spaces::Software

  belongs_to :owner, class_name: 'User', foreign_key: :owner_id
  validates :description, presence: true, uniqueness: { scope: :owner_id }
  has_many :space_users, dependent: :destroy
  has_many :users, through: :space_users
  has_many :links, dependent: :destroy
  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :suppliers, dependent: :destroy
  has_many :products, dependent: :destroy
  has_many :sales, dependent: :destroy

  # TODO: check if extra_units deleted are not used

  def total_final_amount_inc_tax
    sales.pluck(:final_amount_inc_tax).sum
  end

  def total_final_amount_exc_tax
    sales.pluck(:final_amount_exc_tax).sum
  end

  def members
    users.including(owner)
  end

  def confirmed_member?(user)
    user.confirmed? && members.include?(user)
  end

  def unconfirmed_member?(user)
    !user.confirmed? && members.include?(user)
  end
end

app/models/spaces/zelty/connect.rb
# frozen_string_literal: true

require 'net/http'

module Spaces
  module Zelty
    class Connect
      attr_reader :space

      def initialize(space)
        @space = space
        @uri = URI.parse("https://api.zelty.fr/2.7/orders")
        token = @space.software_api_details['token']
        @headers = {
          'Authorization' => "Bearer #{token}",
          'Content-Type' => 'application/json',
          'Accept' => 'application/json'
        }
      end

      def connect
        # result = JSON.parse(call).deep_symbolize_keys

        # result[:errno].zero? ? proceed(result) : raise
      end

      def call(from: (Date.today - 1.day).to_s, to: Date.today.to_s,
               offset: 0, limit: 100)
        params = { from:, to:, offset:, limit:, 'expand[]': 'items' }
        @uri.query = URI.encode_www_form(params)
        Net::HTTP.get(@uri, @headers)
      end
    end
  end
end

app/models/spaces/zelty/import.rb
# frozen_string_literal: true

require 'net/http'

module Spaces
  module Zelty
    class Import
      attr_reader :space

      def initialize(space)
        @space = space
        @uri = URI.parse("https://api.zelty.fr/2.7/orders")
        token = @space.software_api_details['token']
        @headers = {
          'Authorization' => "Bearer #{token}",
          'Content-Type' => 'application/json',
          'Accept' => 'application/json'
        }
      end

      def import
        result = JSON.parse(call).deep_symbolize_keys

        result[:errno].zero? ? proceed(result) : raise
      end

      def call(from: (Date.today - 1.day).to_s, to: Date.today.to_s,
               offset: 0, limit: 100)
        params = { from:, to:, offset:, limit:, 'expand[]': 'items' }
        @uri.query = URI.encode_www_form(params)
        Net::HTTP.get(@uri, @headers)
      end

      private

      # convert the last 10 orders into sales
      def proceed(result)
        result[:orders].reverse.each do |order|
          base_sale.create_with(
            details: order,
            status: order[:status],
            final_amount_inc_tax: order.dig(:price, :final_amount_inc_tax),
            final_amount_exc_tax: order.dig(:price, :final_amount_exc_tax),
            created_at: order[:created_at]
          ).find_or_create_by!(uuid: order[:uuid], uid: order[:id])
        end
      end

      def base_sale
        Sale.create_with(
          space_id: @space.id,
          kind: 'ZeltyNotification',
          webhook_identifier: 'zelty',
          event: 'order/closed'
        )
      end
    end
  end
end

app/controllers/api/v1/spaces_controller.rb
# frozen_string_literal: true

module Api
  module V1
    class SpacesController < Api::V1::BaseController
      before_action :set_space, only: %i[show]

      def index
        @spaces = Space.all
      end

      def show; end

      private

      def set_space
        @space = Space.find(params[:id])
      end
    end
  end
end

app/controllers/spaces/users_controller.rb
# frozen_string_literal: true

module Spaces
  class UsersController < ApplicationController
    before_action :set_space, only: %i[create]
    before_action :authenticate_user!, except: %i[create]

    def create
      @space_user = SpaceUser.new(space_user_params)
      @space_user.space = @space

      if @space_user.save
        warden.set_user(@space_user.user, {}) unless user_signed_in?

        render_turbo_stream
      else
        flash.now[:error] = @space_user.errors.full_messages
        render_flash
      end
    end

    private

    def set_space
      @space = Space.find(params[:space_id])
    end

    def render_turbo_stream
      user = @space_user.user
      partial = @space.confirmed_member?(user) ? 'spaces/users/success' : 'spaces/users/unconfirmed'
      render turbo_stream: turbo_stream.update(:space_users, partial:)
    end

    def space_user_params
      params.require(:space_user).permit(user_params)
    end

    def user_params
      # params[:space_user][:user_id].present?
      return [:user_id] if user_signed_in?

      [user_attributes: %i[email password password_confirmation]]
    end
  end
end

app/controllers/spaces_controller.rb
# frozen_string_literal: true

class SpacesController < ApplicationController
  load_and_authorize_resource
  before_action :set_space, only: %i[edit show update]

  def index
    @spaces = Space.accessible_by(current_ability).order(description: :asc)
    @pagy, @spaces = pagy(@spaces, items: 5)
  end

  def show; end

  def new
    @space = Space.new
    @space.owner = current_user
  end

  def create
    @space = Space.new(space_params)
    @space.owner = current_user
    assign_extra_attributes
    render_form(:create)
  end

  def edit
    set_assign_attributes
  end

  def update
    @space.assign_attributes(space_params)
    assign_extra_attributes
    render_form(:update)
  end

  def destroy
    if @space.destroy
      flash[:success] = I18n.t('spaces.destroy_success')
      redirect_to spaces_path
    else
      render_general_error
    end
  end

  private

  def set_assign_attributes
    %i[token restaurant_key].each do |key|
      @space.assign_attributes("#{key}": @space.software_api_details[key.to_s])
    end
  end

  def assign_extra_attributes
    @space.extra_units = params.dig(:space, :extra_units)&.split(',')
    %i[token restaurant_key].each do |key|
      if @space.send(key).present?
        @space.software_api_details[key.to_s] = @space.send(key)
      else
        @space.software_api_details.delete(key.to_s)
      end
    end
  end

  def render_form(method)
    respond_to do |format|
      if params[:commit].present? && @space.save
        flash[:success] = I18n.t("spaces.#{method}_success")
        format.html { redirect_to @space }
      else
        build_spaces_attributes
        format.turbo_stream { render_form_turbo_stream(**form_locals) }
      end
    end
  end

  def build_spaces_attributes
    @field_submitter = params.dig(:space, :field_submitter)
  end

  def form_locals
    { classes_name: 'spaces', model: @space, locals: { space: @space } }
  end

  def set_space
    @space = Space.find(params[:id])
  end

  def space_params
    params.require(:space).permit(:description, :software, :token, :restaurant_key, user_ids: [])
  end
end

app/helpers/spaces_helper.rb
module SpacesHelper
  def software_name(software)
    t("spaces.softwares.#{software}")
  end

  def softwares_list
    Space::SOFTWARES.map { |software| [software_name(software), software] }
  end
end

app/views/spaces/_form.html.erb
<%= turbo_frame_tag :space, data: {
  controller: "toggle-attribute",
  'toggle-attribute-target': 'element',
  'category': 'turbo_frame',
  'attribute-change': 'target',
  'active-value': '_top' } do %>

  <div class="w-auto lg:w-1/2">
    <%= form_with model: @space, builder: TailwindBuilder,
                  data: { 'toggle-attribute-target': 'element',
                          'category':                'form',
                          'attribute-change':        'novalidate',
                          'active-value':            true } do |form| %>
      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= form.text_field :description, placeholder: " " %>
        <%= form.label :description %>
      </div>
      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= form.text_field :extra_units, placeholder: " ", value: @space.extra_units.join(',') %>
        <%= form.label :extra_units %>
      </div>
      <div class="flex my-8 items-center justify-between">
        <%= form.label :software, class: "relative", style: "top: 0px; transform: none !important;" %>
        <%= form.select(:software,
                        options_for_select(softwares_list, @space.software),
                        {},
                        { data:     { controller:  "slim-select submit-form",
                                      placeholder: t('actions.search'),
                                      "no-result": t('alert.none', class_name: t('software', scope: 'activerecord.attributes.space').pluralize.downcase),
                                      action: 'toggle-attribute#toggle change->submit-form#submit',
                                      'category': 'form',
                                      'submit-form-auto-submit-value': true,
                                      'submit-form-prevent-validation-value': true },
                          class:    "w-full lg:w-1/2 ml-6" }) %>
      </div>
      <% if form.object.software == 'zelty' %>
        <div class="relative my-8 border-b-2 focus-within:border-blue-500">
          <%= form.text_field :token, placeholder: " " %>
          <%= form.label :token %>
        </div>
      <% elsif form.object.software == 'tiller' %>
        <div class="relative my-8 border-b-2 focus-within:border-blue-500">
          <%= form.text_field :api_key, placeholder: " " %>
          <%= form.label :api_key %>
        </div>
        <div class="relative my-8 border-b-2 focus-within:border-blue-500">
          <%= form.text_field :restaurant_key, placeholder: " " %>
          <%= form.label :restaurant_key %>
        </div>
      <% end %>
      <div class="flex my-8 items-center justify-between">
        <%= form.label :users, class: "relative", style: "top: 0px; transform: none !important;" %>
        <%= form.select(:user_ids,
                        User.excluding(@space.owner).order(:email).pluck(:email, :id),
                        {},
                        { data:     { controller:  "slim-select",
                                      placeholder: t('actions.search'),
                                      "no-result": t('alert.none', class_name: t('user', scope: 'activerecord.models').pluralize.downcase)  },
                          multiple: true,
                          class:    "w-full lg:w-1/2 ml-6" }) %>
      </div>
      <div class="actions">
        <%= form.hidden_field :field_submitter, id: 'field_submitter' %>
        <%= form.submit t('actions.submit'), data: {
          action: 'toggle-attribute#toggle',
          'category': 'turbo_frame',
        } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/spaces/_header.html.erb
<%= space.description %>
<div class="text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700 pt-5 mb-5">
  <ul class="flex flex-wrap -mb-px">
    <% %w[sales products orders items suppliers spaces].each do |tab| %>
      <li class="me-2">
        <% link = '#' %>
        <% link = space_sales_path(space_id: space.id) if tab == 'sales' %>
        <% link = space_products_path(space_id: space.id) if tab == 'products' %>
        <% link = space_orders_path(space_id: space.id) if tab == 'orders' %>
        <% link = space_items_path(space_id: space.id) if tab == 'items' %>
        <% link = space_suppliers_path(space_id: space.id) if tab == 'suppliers' %>
        <% link = space_path(id: space.id) if tab == 'spaces' %>
        <% if params[:controller] == tab %>
          <%= link_to t("#{tab}.index.tab"), link, "aria-current": "page", class: "inline-block p-4 text-blue-600 border-b-2 border-blue-600 rounded-t-lg active dark:text-blue-500 dark:border-blue-500" %>
        <% else %>
          <%= link_to t("#{tab}.index.tab"), link, class: "inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/spaces/_home.html.erb
  <div class="py-5">
    <%= space.sales.count %> <%= t('sale', scope: 'activerecord.models').pluralize(space.sales.count) %> (API)
    <br>
    Total <%= t('final_amount_inc_tax', scope: 'activerecord.attributes.sale') %> : <%= space.total_final_amount_inc_tax.fdiv(100) %> €
    <br>
    Total <%= t('final_amount_exc_tax', scope: 'activerecord.attributes.sale') %> : <%= space.total_final_amount_exc_tax.fdiv(100) %> €
  </div>

  <% space.sales.order(created_at: :desc).each do |sale| %>
    <%= link_to space_sale_path(sale, space_id: space.id), data: { turbo: false } do %>
      <div><u><%= t('sale', scope: 'activerecord.models') %> #<%= sale.uid %> (<%= sale.uuid %>)</u></div>
    <% end %>
  <% end %>

app/views/spaces/_main.html.erb
<%= turbo_frame_tag :space do %>
  <%= render 'spaces/header', space: %>

  <%= render 'spaces/settings', space: %>
<% end %>

app/views/spaces/_settings.html.erb
<div class="flex">
  <% if can? :manage, space %>
    <%= link_to t('actions.edit'), edit_space_path(space), data: { turbo: false }, class: "text-blue-400 hover:text-blue-500 hover:underline" %>
     | <%= button_to t('actions.delete'), space_path(space), method: :delete, form: { data: { turbo_confirm: t('spaces.destroy_confirm') } }, class: "text-red-400 hover:text-red-500 hover:underline" %>
  <% end %>
</div>
<div class="py-5">
  <%= t('owner_id', scope: 'activerecord.attributes.space') %> : <%= space.owner.email %>
</div>
<div class="py-5">
  <%= t('users', scope: 'activerecord.attributes.space') %> :
  <br>
  <% space.users.order(confirmed: :desc).each do |user| %>
    <%= user.email %> <%= "(#{t('users.not_confirmed')})" if space.unconfirmed_member?(user) %>
    <br>
  <% end %>
</div>
<div class="py-5">
  <%= t('software', scope: 'activerecord.attributes.space') %> : <%= software_name(space.software) %>
  <% if space.software_connected_at? %>
    (<%= t('software_connected_at', scope: 'activerecord.attributes.space') %> : <%= date(space.software_connected_at) %>)
  <% end %>
</div>

<div class="py-5">
  <%= t('software_api_details', scope: 'activerecord.attributes.space') %> :
  <pre>
    <%= JSON.pretty_generate(space.software_api_details) %>
  </pre>
</div>
<% if space.extra_units.any? %>
  <div class="py-5">
    <%= t('extra_units', scope: 'activerecord.attributes.space') %> : <%= space.extra_units.to_sentence %>
  </div>
<% else %>
  <%= t('alert.none', class_name: t('extra_units', scope: 'activerecord.attributes.space').downcase) %>
<% end %>

<% if can? :manage, space %>
  <div class="border my-8 py-5 p-2">
    <%= t('links.description') %> <br>
    <% if current_user.available_link(space) %>
      <%= render 'links/url', link: current_user.available_link(space) %>
    <% else %>
      <%= render 'links/form', disabled: false %>
    <% end %>
  </div>
<% end %>

app/views/spaces/_space.html.erb
<%= link_to space_path(space), data: { turbo: false } do %>
  <div class="w-full text-center bg-transparent my-5 py-5 px-5 border rounded hover:bg-blue-500 hover:text-white hover:border-transparent">
    <%= space.description %>
  </div>
<% end %>

app/views/spaces/_tabs.html.erb
<div class="text-sm font-medium text-center text-gray-500 border-b border-gray-200 dark:text-gray-400 dark:border-gray-700 pt-5 mb-5">
  <ul class="flex flex-wrap -mb-px">
    <% %w[spaces orders items suppliers].each do |tab| %>
      <li class="me-2">
        <% link = '#' %>
        <% link = space_suppliers_path(space_id: space.id) if tab == 'suppliers' %>
        <% link = space_path(id: space.id) if tab == 'spaces' %>
        <% if params[:controller] == tab %>
          <%= link_to tab.singularize.capitalize, link, "aria-current": "page", class: "inline-block p-4 text-blue-600 border-b-2 border-blue-600 rounded-t-lg active dark:text-blue-500 dark:border-blue-500" %>
        <% else %>
          <%= link_to tab.singularize.capitalize, link, class: "inline-block p-4 border-b-2 border-transparent rounded-t-lg hover:text-gray-600 hover:border-gray-300 dark:hover:text-gray-300" %>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/spaces/edit.html.erb
<%= render 'form' %>

app/views/spaces/index.html.erb
<%= turbo_frame_tag :space do %>
  <% if can? :create, Space %>
    <%= link_to t('spaces.new'), new_space_path, data: { turbo: false }, class: 'text-center bg-gray-200 hover:bg-gray-300 text-dark font-semibold py-2 px-4 border-transparent rounded' %>
    <br><br>
  <% end %>
  <%#= render 'shared/search_and_filter', search_url: spaces_url %>
  <% if @spaces.count.zero? %>
    <p><%= t('alert.none', class_name: t('space', scope: 'activerecord.models').pluralize.downcase) %></p>
  <% else %>
    <%= turbo_frame_tag :spaces do %>
      <%= render @spaces %>
      <% if @pagy.next %>
        <%= turbo_frame_tag :spaces, loading: :lazy, src: url_for(only_path: false, params: { page: @pagy.next }.merge(request.query_parameters.except(:page))) do %>
          <div class="flex justify-center items-center">
            <div class="w-1/2">
              <%= render partial: 'shared/spinner' %>
            </div>
          </div>
        <% end %>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/spaces/new.html.erb
<%= render 'form' %>

app/views/spaces/show.html.erb
<%= turbo_frame_tag :content do %>
  <%= render 'spaces/main', space: @space %>
<% end %>