config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  locales = I18n.available_locales.join('|')
  scope '(:locale)', locale: /#{locales}/ do
    devise_for :users
    # Defines the root path route ("/")
    # root "articles#index"
    root 'posts#index'
    resources :posts
    resources :spaces do
      resources :users, only: %i[create], controller: 'spaces/users'
      resources :products
      resources :items
      resources :suppliers
      resources :orders
      resources :sales
    end
    resources :orders, only: %i[] do
      resource :purchases, only: %i[create update destroy]
    end
    resources :products, only: %i[] do
      resource :sales, only: %i[create  destroy], controller: 'products/sales'
    end


    resources :links, only: %i[show create destroy], param: :sku
    resources :users, only: %i[index edit update destroy]
    get '/open-modal', to: 'pages#open_modal', as: 'open_modal'
  end
end

app/views/shared/_dropdown.html.erb
<div data-controller="dropdown"
     data-dropdown-listen-click-value="<%= is_closing_on_click %>"
     class="relative inline-block text-left">

  <button data-action="click->dropdown#process"
          data-dropdown-target="button"
          type="button"
          class="inline-flex justify-center w-full rounded-md border border-gray-300 shadow-sm px-4 py-2 bg-white text-sm font-medium text-gray-700 hover:bg-gray-50 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-100 focus:ring-blue-500" id="menu-button" aria-expanded="true" aria-haspopup="true">
    <div class="hidden lg:block"><%= button_label_lg %></div> <div class="block lg:hidden"><%= button_label_sm %></div>
    <!-- Heroicon name: solid/chevron-down -->
    <svg class="lg:-mr-1 lg:ml-2 h-5 w-5 <%= "rotate-180" unless is_top %>" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
      <path fill-rule="evenodd" d="M5.293 7.293a1 1 0 011.414 0L10 10.586l3.293-3.293a1 1 0 111.414 1.414l-4 4a1 1 0 01-1.414 0l-4-4a1 1 0 010-1.414z" clip-rule="evenodd" />
    </svg>
  </button>

  <div data-dropdown-target="content"
       class="z-10 origin-top-right absolute mt-2 min-w-fit w-full rounded-md
              shadow-lg bg-white ring-1 ring-black ring-opacity-5 focus:outline-none
              <%= 'hidden' unless by_default_visible %> <%= 'right-0' unless is_left %> <%= 'bottom-[45px]' unless is_top %> " role="menu" aria-orientation="vertical" aria-labelledby="menu-button" tabindex="-1">
    <div class="py-1" role="none">
      <!-- Active: "bg-gray-100 text-gray-900", Not Active: "text-gray-700" -->
      <%= content %>
    </div>
  </div>
</div>

app/views/shared/_dropdown_link.html.erb
<%= link_to title,
            deactivated ? '#' : path, data: { turbo: },
            class: "block w-full text-left #{'hover:bg-blue-500 hover:text-white' unless deactivated } text-gray-700 block px-4 py-2 text-sm" %>

app/views/shared/_flash.html.erb
<% flash.each do |type, message| %>
  <% if %w[error].include?(type) %>
    <div class="bg-red-100 border border-red-400 text-red-700 pl-2 pr-8 py-3 rounded relative mb-5" role="<%= type %>" data-controller="remove">
  <% elsif type == 'alert' %>
    <div class="bg-yellow-100 border border-yellow-400 text-yellow-700 pl-2 pr-8 py-3 rounded relative mb-5" role="<%= type %>" data-controller="remove">
  <% elsif type == 'success' %>
    <div class="bg-green-100 border border-green-400 text-green-700 pl-2 pr-8 py-3 rounded relative mb-5" role="<%= type %>" data-controller="remove">
  <% elsif type == 'notice' %>
    <div class="bg-green-100 border border-green-400 text-green-700 pl-2 pr-8 py-3 rounded relative mb-5" role="<%= type %>" data-controller="remove">
  <% end %>
    <span class="block mr-8">
      <% if message.kind_of?(Array) %>
        <ul>
          <% message.each do |msg|%>
            <li class="pl-2"><%= msg %></li>
          <% end %>
        </ul>
      <% else %>
        <%= message %>
      <% end %>
    </span>
    <span class="absolute top-0 bottom-0 right-0 px-4 py-3">
      <svg class="fill-current h-6 w-6 cursor-pointer" role="button" xmlns="" viewBox="0 0 20 20" data-action="click->remove#proceed">
        <title>Close</title>
        <path d="M14.348 14.849a1.2 1.2 0 0 1-1.697 0L10 11.819l-2.651 3.029a1.2 1.2 0 1 1-1.697-1.697l2.758-3.15-2.759-3.152a1.2 1.2 0 1 1 1.697-1.697L10 8.183l2.651-3.031a1.2 1.2 0 1 1 1.697 1.697l-2.758 3.152 2.758 3.15a1.2 1.2 0 0 1 0 1.698z"/>
      </svg>
    </span>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="w-full sticky top-0 bg-white py-5">
  <div class="w-full flex flex-wrap items-center justify-between">
    <div class="px-2 lg:px-4">
      <%= link_to t('actions.home'), root_path, data: { turbo: false }, class: "block text-center bg-gray-200 hover:bg-gray-300 text-dark font-semibold py-2 px-4 border-transparent rounded" %>
    </div>
    <div class="flex flex-wrap px-2">
      <% if user_signed_in? && current_user.admin? %>
        <%# link_to 'Modal', open_modal_path, class: "block text-center bg-gray-200 hover:bg-gray-300 text-dark font-semibold py-2 px-4 border-transparent rounded" %>
      <% end %>
    </div>
    <div class="px-2 lg:px-4">
      <%= dropdown button_label_lg:  t('actions.navigation.lg'),
                   button_label_sm:  t('actions.navigation.sm'),
                   is_left:          false,
                   is_top:           true,
                   responsive_title: false do %>
        <%= dropdown_link t('spaces.index.title'), spaces_path, turbo: false if user_signed_in? && current_user.confirmed? %>
        <%= dropdown_link t('spaces.new'), new_space_path, turbo: false if can? :manage, Space %>
        <%= dropdown_link t('posts.new'), new_post_path, turbo: false if can? :create, Post %>
        <%= dropdown_link t('users.index.title'), users_path, turbo: false if can? :manage, User %>
        <% if user_signed_in? %>
          <%= dropdown_link t('devise.log_out'), destroy_user_session_path, turbo: false %>
        <% else %>
          <%= dropdown_link t('devise.sign_up'), new_user_registration_path, turbo: false %>
          <%= dropdown_link t('devise.log_in'), new_user_session_path, turbo: false %>
        <% end %>
      <% end %>
      <%= dropdown button_label_lg:  I18n.locale.upcase,
                   button_label_sm:  I18n.locale.upcase,
                   is_left:          false,
                   is_top:           true,
                   responsive_title: false do %>
        <% I18n.available_locales.each do |locale| %>
          <% current_locale = locale == I18n.locale %>
          <%= dropdown_link locale.to_s.upcase, url_for(locale: locale), turbo: false, deactivated: current_locale %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag :post_form_modal,
    data: { "controller": "modal-display" } do %>
  <!-- This example requires Tailwind CSS v2.0+ -->
  <div class="relative z-30" aria-labelledby="modal-title" role="dialog" aria-modal="true">
    <!--
      Background backdrop, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="fixed inset-0 bg-gray-500 bg-opacity-75 transition-opacity duration-300 opacity-0" data-modal-display-target="background"></div>

    <div class="fixed z-10 inset-0 overflow-y-auto">
      <div class="flex items-end sm:items-center justify-center min-h-full p-4 text-center sm:p-0">
        <!--
          Modal panel, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            To: "opacity-100 translate-y-0 sm:scale-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100 translate-y-0 sm:scale-100"
            To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        -->
        <div class="relative bg-white rounded-lg px-4 pt-14 pb-4 text-left shadow-xl transform transition-all w-full m-1 ease-out duration-300 opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
             data-modal-display-target="panel">
          <div class="absolute top-0 right-0 pt-4 pr-4">
            <button type="button" class="bg-white rounded-md text-gray-400 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500"
                    data-action="click->modal-display#close">
              <span class="sr-only">Close</span>
              <!-- Heroicon name: outline/x -->
              <svg class="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
                <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
          <%= content %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_spinner.html.erb
<div class="flex justify-center items-center">
  <svg class="h-1/2 w-1/2 text-sm fill-neutral-200 animate-spin" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 512"><!--! Font Awesome Pro 6.2.0 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license (Commercial License) Copyright 2022 Fonticons, Inc. --><path d="M304 48c0-26.5-21.5-48-48-48s-48 21.5-48 48s21.5 48 48 48s48-21.5 48-48zm0 416c0-26.5-21.5-48-48-48s-48 21.5-48 48s21.5 48 48 48s48-21.5 48-48zM48 304c26.5 0 48-21.5 48-48s-21.5-48-48-48s-48 21.5-48 48s21.5 48 48 48zm464-48c0-26.5-21.5-48-48-48s-48 21.5-48 48s21.5 48 48 48s48-21.5 48-48zM142.9 437c18.7-18.7 18.7-49.1 0-67.9s-49.1-18.7-67.9 0s-18.7 49.1 0 67.9s49.1 18.7 67.9 0zm0-294.2c18.7-18.7 18.7-49.1 0-67.9S93.7 56.2 75 75s-18.7 49.1 0 67.9s49.1 18.7 67.9 0zM369.1 437c18.7 18.7 49.1 18.7 67.9 0s18.7-49.1 0-67.9s-49.1-18.7-67.9 0s-18.7 49.1 0 67.9z"/></svg>
</div>