config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  locales = I18n.available_locales.join('|')
  scope '(:locale)', locale: /#{locales}/ do
    devise_for :users
    # Defines the root path route ("/")
    # root "articles#index"
    root 'posts#index'
    resources :posts
    resources :spaces do
      resources :users, only: %i[create], controller: 'spaces/users'
      resources :products
      resources :items
      resources :suppliers
      resources :orders
      resources :sales
    end
    resources :orders, only: %i[] do
      resource :purchases, only: %i[create update destroy]
    end
    resources :products, only: %i[] do
      resource :sales, only: %i[create  destroy], controller: 'products/sales'
    end


    resources :links, only: %i[show create destroy], param: :sku
    resources :users, only: %i[index edit update destroy]
    get '/open-modal', to: 'pages#open_modal', as: 'open_modal'
  end
end

app/models/concerns/products/sale.rb
# frozen_string_literal: true

module Products
  module Sale
    extend ActiveSupport::Concern

    # false is removing a sale and adding back item quantity
    def process_sale(sale: true)
      Product.transaction do
        increment = sale ? 1 : -1
        update!(sales_count: reload.sales_count + increment)
        product_items.each do |product_item|
          increment = sale ? -1 * product_item.gross_quantity : product_item.gross_quantity
          item = product_item.item
          item.update!(actual_quantity: item.actual_quantity + increment)
        end
      end
    end
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  include Products::Sale

  belongs_to :space
  has_many :product_items, dependent: :destroy
  has_many :items, through: :product_items

  accepts_nested_attributes_for :product_items, allow_destroy: true

  validates :description, presence: true, uniqueness: { scope: :space_id }
  validates :price, presence: true

  scope :description_query, lambda { |description|
    return if description.blank?

    where(arel_table[:description].matches("%#{I18n.transliterate(description)}%"))
  }
end

app/controllers/products/sales_controller.rb
# frozen_string_literal: true

module Products
  class SalesController < ApplicationController
    authorize_resource class: false
    before_action :set_product

    def create
      if @product.process_sale
        flash.now[:success] = I18n.t('products.sales.create_success')
        render_product_show
      else
        render_general_error
      end
    end

    def destroy
      if @product.process_sale(sale: false)
        flash.now[:success] = I18n.t('products.sales.destroy_success')
        render_product_show(sale: false)
      else
        render_general_error
      end
    end

    private

    def render_product_show(sale: true)
      @turbo_stream_data = [
        turbo_stream.update(:"product_#{@product.id}_sales_count", @product.sales_count),
        turbo_stream.update(:sale, partial: 'sales/main', locals: { product: @product, space: @product.space, sale: }),
        turbo_stream.update('flash', partial: 'shared/flash')
      ]

      render turbo_stream: @turbo_stream_data
    end

    def set_product
      @product = Product.find(params[:product_id])
    end
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  load_and_authorize_resource

  before_action :set_space
  before_action :set_product, except: %i[index new create]

  def index
    @products = products_query
    @pagy, @products = pagy(@products, products: 20)
  end

  def new
    @product = @space.products.build
    @product.product_items.build
  end

  def show; end

  def create
    @product = @space.products.build(product_params)

    render_form(:create)
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product.assign_attributes(product_params)

    render_form(:update)
  end

  def destroy
    if @product.destroy
      flash[:success] = I18n.t('products.destroy_success')
      redirect_to space_products_path(space: @space)
    else
      render_general_error
    end
  end

  private

  def products_query
    @space.products
          .description_query(params[:search])
          .order(:description)
  end

  def render_form(method)
    respond_to do |format|
      if params[:commit].present? && @product.save
        flash[:success] = I18n.t("products.#{method}_success")
        format.html { redirect_to space_product_path(@product, space_id: @space.id) }
      else
        build_product_attributes
        format.turbo_stream { render_form_turbo_stream(**form_locals) }
      end
    end
  end

  def build_product_attributes
    @field_submitter = params.dig(:product, :field_submitter)
    @product.product_items.build if params[:add_item]
  end

  def form_locals
    { classes_name: 'products',
      model: @product,
      locals: { product: @product, space: @product.space } }
  end

  def product_params
    params.require(:product).permit(
      :description,
      product_items_attributes: %i[id product_id item_id gross_quantity net_quantity quantity_ratio _destroy]
    )
  end

  def set_space
    @space = Space.find(params[:space_id])
  end

  def set_product
    @product = Product.find(params[:id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= turbo_frame_tag :space, data: {
  controller: "toggle-attribute",
  'toggle-attribute-target': 'element',
  'category': 'turbo_frame',
  'attribute-change': 'target',
  'active-value': '_top' } do %>
  <%= render "spaces/header", space: %>

  <div class="w-auto lg:w-1/2 pt-5">
    <%= form_with model: [space, product],
                  builder: TailwindBuilder,
                  data: { 'toggle-attribute-target': 'element',
                          'category':                'form',
                          'attribute-change':        'novalidate',
                          'active-value':            true } do |form| %>
      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= form.text_field :description, placeholder: " " %>
        <%= form.label :description %>
      </div>
      <%= render partial: 'products/product_items_fields',
                 locals: { form:, space_item_datas: space.items.order(:description).pluck(:description, :id) } %>
      <div class="field text-right">
        <%= button_tag name: 'add_item',
                      class: 'text-center bg-gray-200 hover:bg-gray-300 text-dark font-semibold py-2 px-4 border-transparent rounded',
                      data: {
                        controller: 'submit-form',
                        action: 'toggle-attribute#toggle change->submit-form#submit',
                        'category': 'form',
                        'submit-form-auto-submit-value': true,
                        'submit-form-prevent-validation-value': true
                      } do %>
          <% t('products.form.add_item') %>
        <% end %>
      </div>
      <div class="field">
        <%= form.submit t('actions.submit'), data: {
          action: 'toggle-attribute#toggle',
          'category': 'turbo_frame',
        } %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/products/_item.html.erb
<div class="table-row-group">
  <div class="<%= class_names('table-row', index&.odd? ? 'bg-white' : 'bg-gray-50') %>">
    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 font-medium text-gray-900">
      <%= index + 1 %>.
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= item.description %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= item.uid %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= item.supplier.name %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= unit_name(item.unit) %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= product_item.net_quantity %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= product_item.gross_quantity %>
    </div>

    <div class="table-cell px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-900">
      <%= product_item.quantity_ratio %>
    </div>
  </div>
</div>

app/views/products/_main.html.erb
<%= turbo_frame_tag :space do %>
  <%= render "spaces/header", space: %>
  <% if can? :manage, product %>
    <div class="flex">
      <%= link_to t('actions.edit'), edit_space_product_path(product, space_id: space.id), class: "text-blue-400 hover:text-blue-500 hover:underline" %>
       | <%= button_to t('actions.delete'), space_product_path(product, space_id: space.id), method: :delete, form: { data: { turbo_confirm: t('products.destroy_confirm') } }, class: "text-red-400 hover:text-red-500 hover:underline" %>
    </div>
  <% end %>
  <br>
  <br><%= t('description', scope: 'activerecord.attributes.product') %> : <%= product.description %>
  <br>
  <br><%= t('sales_count', scope: 'activerecord.attributes.product') %> :
  <%= turbo_frame_tag :"product_#{product.id}_sales_count" do %><%= product.sales_count %><% end %>
  <br>
  <br>
  <%= render 'products/table', product: %>
  <br><br>
  <div class="flex justify-between items-center flex-wrap">
    <%= button_to t('products.sales.index.create'), product_sales_path(product), method: :post, class: "text-center bg-transparent hover:bg-green-500 text-green-700 font-semibold hover:text-white py-2 px-4 ml-6 border border-green-500 hover:border-transparent rounded" %>
    <%= button_to t('products.sales.index.destroy'), product_sales_path(product), method: :delete, class: "text-center bg-transparent hover:bg-red-500 text-red-700 font-semibold hover:text-white py-2 px-4 ml-6 border border-red-500 hover:border-transparent rounded" %>
  </div>

  <%= turbo_frame_tag :sale do %>
  <% end %>
<% end %>

app/views/products/_product.html.erb
<%= link_to space_product_path(product, space_id: space.id) do %>
  <div class="w-full text-center bg-transparent my-2 py-2 px-5 border rounded hover:bg-blue-500 hover:text-white hover:border-transparent">
    <%= product.description %>
    <br> <%= t('sales_count', scope: 'activerecord.attributes.product' ) %> : <%= product.sales_count %>
  </div>
<% end %>

app/views/products/_product_items_fields.html.erb
<%= form.fields_for :product_items do |product_item| %>
  <div class="mt-3 <%= 'hidden' if product_item.object._destroy %>"
       data-controller="toggle-attribute">
    <%= product_item.hidden_field :id %>
    <%= product_item.hidden_field :product_id %>
    <div class="flex">
      <div class="flex flex-col px-6 justify-center">
        <div>
          <%= product_item.label :item_id, class: "relative", style: "top: 0px; transform: none !important;" %>
          #<%= product_item.options[:child_index] + 1 %>
        </div>
        <%= product_item.select(:item_id,
          space_item_datas,
          {},
          { data:     { controller:  "slim-select",
                        placeholder: t('actions.search'),
                        "no-result": t('alert.none', class_name: t('item', scope: 'activerecord.models').pluralize.downcase)  },
            class:    "w-full lg:w-1/2" }) %>
      </div>

      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= product_item.number_field :net_quantity, step: :any, placeholder: " " %>
        <%= product_item.label :net_quantity %>
      </div>

      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= product_item.number_field :gross_quantity, step: :any, placeholder: " " %>
        <%= product_item.label :gross_quantity %>
      </div>

      <div class="relative my-8 border-b-2 focus-within:border-blue-500">
        <%= product_item.number_field :quantity_ratio, step: :any, placeholder: " " %>
        <%= product_item.label :quantity_ratio %>
      </div>

      <div class="flex grid-cols-1 lg:grid-cols-6 gap-2">
        <%# if product_item.options[:child_index].positive? %>
          <%= button_tag name: "destroy_item_#{product_item.options[:child_index]}",
                         data: {
                           controller: 'submit-form',
                           action: 'toggle-attribute#toggle change->submit-form#submit',
                           'category': 'form',
                           'submit-form-auto-submit-value': true,
                           'submit-form-prevent-validation-value': true
                         } do %>
            <div class="justify-center items-center order-first lg:order-last">
              <span data-action="click->toggle-attribute#toggle"
                    category="destroy_item_<%=product_item.options[:child_index] %>">
                ❌
              </span>
            </div>
          <% end %>
        <%# end %>
      </div>
    </div>

    <%= product_item.check_box :_destroy,
      class: 'hidden',
      data: {
        'toggle-attribute-target': 'element',
        'category': "destroy_item_#{product_item.options[:child_index]}",
        'attribute-change': 'checked',
        'active-value': '1'
      } %>
  </div>
<% end %>

app/views/products/_search_and_filter.html.erb
<div id="products-search">
  <%= form_with url: space_products_path(space), method: :get, builder: TailwindBuilder, html: { class: "pb-5 flex flex-wrap gap-2", data: { controller: "autosave" } } do |form| %>
    <div class="relative rounded-md shadow-sm">
      <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
        <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
      </div>
      <%= search_field_tag :search,
                          params[:search],
                          class: "pl-10 block w-full rounded-md border-gray-300 shadow-sm",
                          placeholder: t('actions.search'),
                          data: { action: 'keyup->autosave#save' } %>
    </div>
  <% end %>
</div>

app/views/products/_table.html.erb
<div class="flex flex-col">
  <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
    <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
      <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
        <div class="min-w-full divide-y divide-gray-200 table">
          <div class="table-row">
            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              #
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('description', scope: 'activerecord.attributes.item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('uid', scope: 'activerecord.attributes.item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('supplier_id', scope: 'activerecord.attributes.item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('unit', scope: 'activerecord.attributes.item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('net_quantity', scope: 'activerecord.attributes.product_item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('gross_quantity', scope: 'activerecord.attributes.product_item') %>
            </div>

            <div class="table-cell px-6 py-3 bg-gray-50 text-left text-xs leading-4 font-medium text-gray-500 uppercase tracking-wider">
              <%= t('quantity_ratio', scope: 'activerecord.attributes.product_item') %>
            </div>
          </div>

          <% product.product_items.includes(:item).each_with_index do |product_item, index| %>
            <%= render 'products/item', index:, item: product_item.item, product_item: %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<%= render 'products/form', product: @product, space: @space %>

app/views/products/index.html.erb
<%= turbo_frame_tag :space do %>
  <%= render "spaces/header", space: @space %>

  <%= link_to t('products.new'), new_space_product_path(space_id: @space.id), class: "text-center bg-gray-200 hover:bg-gray-300 text-dark font-semibold py-2 px-4 border-transparent rounded" %>
  <br><br>
  <%= render 'products/search_and_filter', space: @space %>

  <% if @products.count.zero? %>
    <p><%= t('alert.none', class_name: t('product', scope: 'activerecord.models').pluralize.downcase) %></p>
  <% else %>
    <%== render partial: 'shared/pagy/nav', locals: { pagy: @pagy } %>
    <%= render @products, space: @space %>
    <%== render partial: 'shared/pagy/nav', locals: { pagy: @pagy } %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= render 'products/form', product: @product, space: @space %>

app/views/products/show.html.erb
<%= render 'main', product: @product, space: @space %>